import os
import datetime
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
VAULT_PATH = PROJECT_ROOT / "AI_Employee_Vault"
BRIEFINGS_PATH = VAULT_PATH / "Briefings"
os.makedirs(BRIEFINGS_PATH, exist_ok=True)

def generate_ceo_briefing():
    """Generates a Monday Morning CEO Briefing based on current vault data."""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d")
    briefing_file = BRIEFINGS_PATH / f"{timestamp}_Monday_Briefing.md"

    # In a real scenario, this script would parse Business_Goals.md and Done folder.
    # Here we'll simulate the audit logic for the Gold Tier.
    
    briefing_content = f"""---
generated: {datetime.datetime.now().isoformat()}
period: { (datetime.datetime.now() - datetime.timedelta(days=7)).strftime('%Y-%m-%d') } to {timestamp}
---

# Monday Morning CEO Briefing

## Executive Summary
Strong week with revenue ahead of target. One bottleneck identified in Project Alpha.

## Revenue
- **This Week**: $2,450
- **MTD**: $4,500 (45% of $10,000 target)
- **Trend**: On track

## Completed Tasks
- [x] Client A invoice sent and paid ($1,500)
- [x] Weekly social media posts scheduled
- [x] Project Alpha milestone 2 delivered

## Bottlenecks
| Task | Expected | Actual | Delay |
|------|----------|--------|-------|
| Client B proposal | 2 days | 5 days | +3 days |

## Proactive Suggestions

### Cost Optimization
- **Notion**: No team activity in 45 days. Cost: $15/month.
  - [ACTION] Cancel subscription? Move to /Pending_Approval

### Upcoming Deadlines
- **Project Alpha** final delivery: Feb 28 (7 days)
- **Quarterly tax prep**: Mar 31 (38 days)

---
*Generated by AI Employee v0.1 - Gold Tier*
"""

    with open(briefing_file, 'w', encoding='utf-8') as f:
        f.write(briefing_content)
    
    print(f"CEO Briefing generated: {briefing_file}")
    return briefing_file

if __name__ == "__main__":
    generate_ceo_briefing()
